dummy: true
simulation: false
experiment_libraries:
  - ECMS_exp
  - samples_exp
experiment_params:
  gamrychannelwait: -1
  gamrychannelsend: 1
sequence_libraries:
  - ECMS_seq
sequence_params:
  gamrychannelwait: -1
  gamrychannelsend: 1
run_type: ecms
root: C:\INST_hlo
servers:
  ORCH:
    host: hte-ecms-03.htejcap.caltech.edu
    port: 8001
    group: orchestrator
    fast: async_orch2
    params:
      enable_op: true
      bokeh_port: 5002
      seqspec_parser_path: helao\specifications\last3months.py
      seqspec_folder_path: C:\INST_hlo\RUNS_SYNCED
    verbose: false
  # IO:
  #   host: hte-ecms-01.htejcap.caltech.edu
  #   port: 8005
  #   group: action
  #   fast: galil_io
  #   params:
  #     galil_ip_str: 192.168.200.232
  #     dev_ai:
  #       cell_pressure_psi: 1
  #     dev_ao: {}
  #     dev_di:
  #       multichannel_valve_done: 1
  #       multichannel_valve_error: 2
  #     dev_do:
  #       gamry_aux: 1
  #       Thorlab_led: 7
  #     monitor_ai:
  #       cell_pressure_psi: 5.0
  NI:
    host: hte-ecms-03.htejcap.caltech.edu
    port: 8006
    group: action
    fast: nidaqmx_server
    params:
      dev_gasvalve:
        '1': dev1/port0/line0
        2A: dev1/port0/line1
        2B: dev1/port0/line2
        3A: dev1/port0/line3
        3B: dev1/port0/line4
        6A: dev1/port1/line5
        6B: dev1/port1/line6
        '7': dev1/port1/line7
      dev_liquidvalve:
        4A: dev1/port0/line5
        4B: dev1/port0/line6
        5A: dev1/port0/line7
        5B: dev1/port1/line0
      dev_pump:
        RecirculatingPeriPump1-dir: dev1/port1/line1
        RecirculatingPeriPump1: dev1/port1/line2
        RecirculatingPeriPump2-dir: dev1/port1/line3
        RecirculatingPeriPump2: dev1/port1/line4
        RecirculatingPeriPump2-maxspd: dev1/port2/line0
  PAL:
    host: hte-ecms-03.htejcap.caltech.edu
    port: 8007
    group: action
    fast: pal_server
    params:
      positions:
        custom:
          cell1_we: cell
  VIS:
    host: hte-ecms-03.htejcap.caltech.edu
    port: 5001
    group: visualizer
    bokeh: action_visualizer
    params:
      doc_name: ECMS Visualizer
  LIVE:
    host: hte-ecms-03.htejcap.caltech.edu
    port: 5004
    group: visualizer
    bokeh: live_visualizer
    params:
      doc_name: Sensor Visualizer
    verbose: false
  MFC:
    host: hte-ecms-03.htejcap.caltech.edu
    port: 8009
    group: action
    fast: mfc_server
    params:
      devices:
        CO2:
          port: COM3
          unit_id: A
    verbose: false


  CALIBRATIONMFC:
    host: hte-ecms-03.htejcap.caltech.edu
    port: 8012 
    group: action
    fast: mfc_server
    params:
      devices:
        Caligas:
          port: COM4 # needs to update
          unit_id: A

  CALIBRATIONMFC2:
    host: hte-ecms-03.htejcap.caltech.edu
    port: 8013 
    group: action
    fast: mfc_server
    params:
      devices:
        Caligas2:
          port: COM6 # needs to update
          unit_id: A

  PSTAT:
    host: hte-ecms-03.htejcap.caltech.edu
    port: 8004
    group: action
    fast: gamry_server
    params:
      dev_id: 0
      filterfreq_hz: 1000.0
      grounded: true
      allow_no_sample: true # would need to remove this later so all samples can be tracked
  CALC:
    host: hte-ecms-03.htejcap.caltech.edu
    port: 8011
    group: action
    fast: calc_server
    params: {}
    verbose: false
  DB:
    host: hte-ecms-03.htejcap.caltech.edu
    port: 8010
    group: action
    fast: dbpack_server
    params:
      aws_config_path: k:/users/hte/.credentials/aws_config.ini
      aws_profile: default
      aws_bucket: helao.data
      api_host: caltech-api.modelyst.com
      testing: false
