dummy: true
simulation: false
# builtin_ref_motorxy:
#   - 44.850974338462315
#   - -107.5622526817081
experiment_libraries:
  - samples_exp
  - HISPEC_exp
  - ECHE_exp
  - ECHEUVIS_exp
  # - UVIS_exp
  # - TEST_exp
# experiment_params:
#   toggle_is_shutter: false
#   gamrychannelwait: -1
#   gamrychannelsend: 0
sequence_libraries:
#   - ECHE_seq
    - HiSPEC_seq
#   - UVIS_T_seq
#   - TEST_seq
# sequence_params:
#   led_wavelengths_nm:
#     - -1
#   led_intensities_mw:
#     - 0.432
#   led_names:
#     - doric_wled
#   led_type: front
#   led_date: 8/16/2022
#   toggle_is_shutter: false
#   gamrychannelwait: -1
#   gamrychannelsend: 0
run_type: hispec
root: C:\INST_hlo
servers:
  ORCH:
    host: hte-eche-11.htejcap.caltech.edu
    port: 8001
    group: orchestrator
    fast: async_orch2
    params:
      enable_op: true
      bokeh_port: 5002
      # seqspec_parser_path: helao\specifications\last3months.py
      seqspec_folder_path: C:\INST_hlo\RUNS_SYNCED
      ignore_heartbeats:
        - ANDOR/acquire
    verbose: true
  MOTOR:
    host: hte-eche-11.htejcap.caltech.edu
    port: 8003
    group: action
    fast: galil_motion
    params:
      enable_aligner: true
      bokeh_port: 5003
      M_instr:
        -   - 1
            - 0
            - 0
            - 0
        -   - 0
            - 1
            - 0
            - 0
        -   - 0
            - 0
            - 1
            - 0
        -   - 0
            - 0
            - 0
            - 1
      count_to_mm:
        A: 0.00015636483
        B: 0.00015623621
      galil_ip_str: 192.168.200.219
      def_speed_count_sec: 10000
      max_speed_count_sec: 25000
      ipstr: 192.168.200.219
      axis_id:
        x: B
        y: A
      axis_zero:
        A: 127.5
        B: 76.5
      timeout: 600
  PSTAT:
    host: hte-eche-11.htejcap.caltech.edu
    port: 8004
    group: action
    fast: biologic_server
    params:
      allow_no_sample: true
      address: 192.168.200.100
      num_channels: 1
      grounded: true
  IO:
    host: hte-eche-11.htejcap.caltech.edu
    port: 8005
    group: action
    fast: galil_io
    params:
      galil_ip_str: 192.168.200.219
      dev_di:
        gamry_ttl0: 1
      dev_do:
        we_vent: 5
        ce_vent: 8
        spec_trig: 1
        we_flow: 2
        we_pump: 7
        ce_pump: 3
        ce_flow: 4
  PAL:
    host: hte-eche-11.htejcap.caltech.edu
    port: 8007
    group: action
    fast: pal_server
    params:
      positions:
        custom:
          cell1_we: cell
  ANDOR:
    host: hte-eche-11.htejcap.caltech.edu
    port: 8011
    group: action
    fast: andor_server
    params:
      dev_id: 0
    hlo_postprocess_script: HiSpEC_process_all
    verbose: true
  VIS:
    host: hte-eche-11.htejcap.caltech.edu
    port: 5001
    group: visualizer
    bokeh: action_visualizer
    params:
      doc_name: ECHE11 Visualizer
  DB:
    host: hte-eche-11.htejcap.caltech.edu
    port: 8010
    group: action
    fast: dbpack_server
    params:
      aws_config_path: k:/users/hte/.credentials/aws_config.ini
      aws_profile: default
      aws_bucket: helao.data
      api_host: caltech-api.modelyst.com
      testing: false
  CALC:
      host: hte-eche-11.htejcap.caltech.edu
      port: 8012
      group: action
      fast: calc_server
      params: {}
      verbose: false


  # ANA:
  #   host: hte-eche-11.htejcap.caltech.edu
  #   port: 8014
  #   group: action
  #   fast: analysis_server
  #   params:
  #     env_file: k:/users/hte/.credentials/helao_data.env
  #     local_only: false
  # CAM:
  #   host: hte-eche-11.htejcap.caltech.edu
  #   port: 8013
  #   group: action
  #   fast: cam_server
  #   params:
  #     axis_ip: 192.168.200.210
  KMOTOR:
    host: hte-eche-11.htejcap.caltech.edu
    port: 8015
    group: action
    fast: kinesis_server
    params:
      axes:
        z:
          serial_no: "49437454"
          pos_scale: 1228800.0  # device to mm
          vel_scale: 65970697.6  # device to mm/s
          acc_scale: 13518.2  # device to mm/s2
          move_limit_mm: 5.0
