dummy: true
simulation: false
# builtin_ref_motorxy:
#   - 44.850974338462315
#   - -107.5622526817081
# experiment_libraries:
#   - samples_exp
#   - ECHE_exp
#   - ECHEUVIS_exp
#   - UVIS_exp
#   - TEST_exp
# experiment_params:
#   toggle_is_shutter: false
#   gamrychannelwait: -1
#   gamrychannelsend: 0
# sequence_libraries:
#   - ECHE_seq
#   - ECHEUVIS_seq
#   - UVIS_T_seq
#   - TEST_seq
# sequence_params:
#   led_wavelengths_nm:
#     - -1
#   led_intensities_mw:
#     - 0.432
#   led_names:
#     - doric_wled
#   led_type: front
#   led_date: 8/16/2022
#   toggle_is_shutter: false
#   gamrychannelwait: -1
#   gamrychannelsend: 0
run_type: htse
root: C:\INST_hlo
servers:
  ORCH:
    host: 127.0.0.1
    port: 8001
    group: orchestrator
    fast: async_orch2
    params:
      enable_op: true
      bokeh_port: 5002
      # seqspec_parser_path: helao\specifications\last3months.py
      seqspec_folder_path: C:\INST_hlo\RUNS_SYNCED
  # MOTOR:
  #   host: hte-eche-10.htejcap.caltech.edu
  #   port: 8003
  #   group: action
  #   fast: galil_motion
  #   params:
  #     enable_aligner: true
  #     bokeh_port: 5003
  #     M_instr:
  #       -   - 1
  #           - 0
  #           - 0
  #           - 0
  #       -   - 0
  #           - 1
  #           - 0
  #           - 0
  #       -   - 0
  #           - 0
  #           - 1
  #           - 0
  #       -   - 0
  #           - 0
  #           - 0
  #           - 1
  #     count_to_mm:
  #       A: 0.00015634502846261243
  #       B: 0.00015624414084471834
  #     galil_ip_str: 192.168.200.234
  #     def_speed_count_sec: 10000
  #     max_speed_count_sec: 25000
  #     ipstr: 192.168.200.234
  #     axis_id:
  #       x: B
  #       y: A
  #     axis_zero:
  #       A: 127.8
  #       B: 76.7
  #     timeout: 600
  # PSTAT:
  #   host: hte-eche-10.htejcap.caltech.edu
  #   port: 8004
  #   group: action
  #   fast: gamry_server2
  #   params:
  #     allow_no_sample: true
  #     dev_id: 0
  #     filterfreq_hz: 1000.0
  #     grounded: true
  # IO:
  #   host: hte-eche-10.htejcap.caltech.edu
  #   port: 8005
  #   group: action
  #   fast: galil_io
  #   params:
  #     galil_ip_str: 192.168.200.234
  #     dev_di:
  #       gamry_ttl0: 1
  #     dev_do:
  #       spec_trig: 5
  #       ir_emitter: 8
  #       doric_wled: 1
  #       we_flow: 2
  #       we_pump: 7
  #       we_vent: 3
  #       ce_pump: 6
  #       ce_vent: 4
  #       # gamry_aux: 1
  #       # led: 8
  #       # doric_led1: 4
  #       # pump_ref_flush: 3
  #       # pump_supply: 2
  #       # doric_led2: 5
  #       # doric_led3: 6
  #       # ir_emitter: 7
  # PAL:
    host: hte-eche-10.htejcap.caltech.edu
    port: 8007
    group: action
    fast: pal_server
    params:
      positions:
        custom:
          cell1_we: cell
  ANDOR:
    host: 127.0.0.1
    port: 8011
    group: action
    fast: andor_server
    params:
      dev_id: 0
  # VIS:
  #   host: hte-eche-10.htejcap.caltech.edu
  #   port: 5001
  #   group: visualizer
  #   bokeh: action_visualizer
  #   params:
  #     doc_name: ECHE10 Visualizer
  # DB:
  #   host: hte-eche-10.htejcap.caltech.edu
  #   port: 8010
  #   group: action
  #   fast: dbpack_server
  #   params:
  #     aws_config_path: k:/users/hte/.credentials/aws_config.ini
  #     aws_profile: default
  #     aws_bucket: helao.data
  #     api_host: caltech-api.modelyst.com
  #     testing: false
  # ANA:
  #   host: hte-eche-10.htejcap.caltech.edu
  #   port: 8014
  #   group: action
  #   fast: analysis_server
  #   params:
  #     env_file: k:/users/hte/.credentials/helao_data.env
  #     local_only: false
  # CAM:
  #   host: hte-eche-10.htejcap.caltech.edu
  #   port: 8013
  #   group: action
  #   fast: cam_server
  #   params:
  #     axis_ip: 192.168.200.210
  # KMOTOR:
  #   host: hte-eche-10.htejcap.caltech.edu
  #   port: 8015
  #   group: action
  #   fast: kinesis_server
  #   params:
  #     axes:
  #       z:
  #         serial_no: "49370234"
  #         pos_scale: 1228800.0  # device to mm
  #         vel_scale: 65970697.6  # device to mm/s
  #         acc_scale: 13518.2  # device to mm/s2
  #         move_limit_mm: 3.0