dummy: true
simulation: true
show_debug: true
experiment_libraries:
  - TEST_exp
sequence_libraries:
  - TEST_seq
run_type: simulation
root: C:/INST_hlo
servers:
  ORCH:
    host: 127.0.0.1
    port: 8011
    group: orchestrator
    fast: async_orch2
    params:
      enable_op: true
      bokeh_port: 5011
      launch_browser: true