"""SyncStorage port: filesystem + cloud-upload operations for the sync domain.

All methods are synchronous. S3 upload methods are stubbed in FsSyncStorage
and implemented in S3SyncStorage (follow-on SP).
"""
from pathlib import Path
from typing import Protocol, runtime_checkable


@runtime_checkable
class SyncStorage(Protocol):
    """Abstract sync operations. Injected into SyncEngine."""

    # Tree inspection
    def list_ymls(self, root: Path) -> list[Path]: ...
    def list_files(self, dir_path: Path, pattern: str = "*") -> list[Path]: ...

    # YAML I/O
    def read_yml(self, path: Path) -> dict: ...
    def write_yml(self, path: Path, data: dict) -> None: ...

    # Progress sidecar I/O
    def read_prg(self, path: Path) -> dict: ...
    def write_prg(self, path: Path, data: dict) -> None: ...
    def remove_prg(self, path: Path) -> None: ...

    # Filesystem mutations
    def move_tree(self, src: Path, dst: Path) -> Path: ...
    def zip_dir(self, path: Path) -> Path: ...
    def try_remove_empty(self, path: Path) -> bool: ...

    # Cloud upload (stubs in FsSyncStorage; real in S3SyncStorage)
    def upload_file(self, local_path: Path, s3_key: str) -> bool: ...
    def upload_bytes(
        self, data: bytes, s3_key: str, content_type: str = "application/json"
    ) -> bool: ...
    def key_exists(self, s3_key: str) -> bool: ...
