dummy: true
simulation: false
builtin_ref_motorxy: # cleaning position
  - -10
  - 10
builtin_ref_motorxy_2: # ref upper
  - -32
  - 35
builtin_ref_motorxy_3: # ref -1
  - -32
  - 27
builtin_ref_motorxy_4: # ref -2
  - -32
  - 19
builtin_ref_motorxy_5:
  - -32
  - 5
builtin_ref_motorxy_6:
  - -32
  - -5
experiment_libraries:
  - ADSS_xtraclean_exp
  - CLAD_exp
  - samples_exp
experiment_params:
  gamrychannelwait: -1
  gamrychannelsend: -1
sequence_libraries:
  - ADSS_seq
  - CLAD_seq
sequence_params:
  gamrychannelwait: -1
  gamrychannelsend: -1
run_type: adss
root: C:\INST_hlo
servers:
  ORCH:
    host: hte-adss-03.htejcap.caltech.edu
    port: 8001
    group: orchestrator
    fast: async_orch2
    params:
      enable_op: true
      bokeh_port: 5002
      seqspec_parser_path: helao\specifications\last3months.py
      seqspec_folder_path: C:\INST_hlo\RUNS_SYNCED
    verbose: true
  MOTOR:
    host: hte-adss-03.htejcap.caltech.edu
    port: 8003
    group: action
    fast: galil_motion
    params:
      enable_aligner: true
      bokeh_port: 5003
      M_instr:
        - - 1
          - 0
          - 0
          - 0
        - - 0
          - 1
          - 0
          - 0
        - - 0
          - 0
          - 1
          - 0
        - - 0
          - 0
          - 0
          - 1
      count_to_mm:
        A: 6.314999998973812e-05
        B: 0.00015627999999717445
        C: 0.00015634000000352077
        D: 0.0003169786106003353
      z_height_mm:
        contact: 11.0
        seal: 20.0
        load: 5.0
      galil_ip_str: 192.168.200.23
      def_speed_count_sec: 10000
      max_speed_count_sec: 25000
      ipstr: 192.168.200.23
      axis_id:
        x: C
        y: B
        z: A
        Rz: D
      axis_zero:
        A: 0.0
        B: 52.0
        C: 77.0
        D: 0.0
      timeout: 600
  PSTAT:
    host: hte-adss-03.htejcap.caltech.edu
    port: 8004
    group: action
    #switch for biologic
    #    fast: biologic_server
    fast: gamry_server2 #
    params:
      #      address: 192.168.200.100
      #      num_channels: 1
      allow_no_sample: true #
      dev_id: 0 #
      filterfreq_hz: 1000.0 #
      grounded: true #
  NI:
    host: hte-adss-03.htejcap.caltech.edu
    port: 8006
    group: action
    fast: nidaqmx_server
    params:
      allow_no_sample: true
      dev_liquidvalve:
        clean_refill: PXI-6284/port1/line3  # V2 -- 3-way valve for cleaning solution (HNO3) to cell / refill reservoir
        work_refill: PXI-6284/port1/line4  # V3 -- 3-way valve for working electrolyte to cell / refill reservoir
        pump_drain: PXI-6284/port1/line5  # V4 -- 3-way valve cell peristaltic pump recirculation / drain 
        water_refill: PXI-6284/port1/line6  # TODO: V5? -- 3-way valve for water to cell / refill reservoir
      dev_gasvalve:
        inlet: PXI-6284/port1/line2  # V1 -- open gas valve
        O2N2toggle: PXI-6284/port2/line0  # 3-way valve for O2/N2 gas switching
      dev_unassigned:
        unassigned0: PXI-6284/port1/line7
        unassigned1: PXI-6284/port2/line1
        unassigned2: PXI-6284/port2/line2
      dev_pump:
        peripump: PXI-6284/port0/line4
        direction: PXI-6284/port0/line0
      dev_fsw:
        done: PXI-6284/port2/line4
        error: PXI-6284/port2/line6
      dev_led:
        led: PXI-6289/port0/line0
  PAL:
    host: hte-adss-03.htejcap.caltech.edu
    port: 8007
    group: action
    verbose: true
    fast: pal_server
    regular_update: true
    params:
      user: RSHS
      key: c:\helao\sshkeys\adss_private_newff.pem
      host: 10.231.100.128
      timeout: 1800
      dev_trigger: NImax
      trigger:
        start: PXI-6284/port2/line5
        continue: PXI-6284/port2/line7
        done: PXI-6284/port2/line3
      cam_file_path: C:\Users\rshs\Desktop\ADSS\adss_psc_methods\HELAO
      cams:
        transfer_tray_tray: tray_to_tray_220214.cam
        transfer_custom_tray: custom_to_tray_220214.cam
        archive: custom_to_tray_220214.cam
        transfer_tray_custom: tray_to_custom_220214.cam
        deepclean: deep_clean_220214.cam
      positions:
        tray1:
          slot1: null
          slot2: null
          slot3: null
        tray2:
          slot1: VT54
          slot2: VT54
          slot3: VT54
        custom:
          elec_res1: reservoir
          elec_res2: reservoir
          cell1_we: cell
  VIS:
    host: hte-adss-03.htejcap.caltech.edu
    port: 5001
    group: visualizer
    bokeh: action_visualizer
    params: {}
  WORKSYRINGE:
    host: hte-adss-03.htejcap.caltech.edu
    port: 8013
    group: action
    fast: syringe_server
    params:
      port: COM3
      pumps:
        zero:
          address: 0
          diameter: 26.7
  CLEANSYRINGE:
    host: hte-adss-03.htejcap.caltech.edu
    port: 8014
    group: action
    fast: syringe_server
    params:
      port: COM4
      pumps:
        one:
          address: 1
          diameter: 26.7
  WATERSYRINGE:
    host: hte-adss-03.htejcap.caltech.edu
    port: 8015
    group: action
    fast: syringe_server
    params:
      port: COM5
      pumps:
        one:
          address: 2
          diameter: 26.7
  LIVE:
    host: hte-adss-03.htejcap.caltech.edu
    port: 5004
    group: visualizer
    bokeh: live_visualizer
    params:
      doc_name: Sensor Visualizer
  DB:
    host: hte-adss-03.htejcap.caltech.edu
    port: 8010
    group: action
    fast: dbpack_server
    params:
      aws_profile: default
      testing: false
    verbose: true
