dummy: false
simulation: false
experiment_libraries:
  - samples_exp
  - ICPMS_exp
  - helao\deploy\test\experiments\TEST_exp.py
sequence_libraries:
  - ICPMS_seq
  - helao\deploy\test\sequences\TEST_seq.py
run_type: icpm
root: C:\INST_hlo
servers:
  ORCH:
    host: hte-icpm-01.htejcap.caltech.edu
    port: 8001
    group: orchestrator
    fast: async_orch2
    params:
      enable_op: true
      bokeh_port: 5002
      seqspec_parser_path: helao\specifications\last3months.py
      seqspec_folder_path: C:\INST_hlo\RUNS_SYNCED
  PAL:
    host: hte-icpm-01.htejcap.caltech.edu
    port: 8007
    group: action
    fast: pal_server
    params:
      positions:
        custom:
          cell1_we: cell
  DB:
    host: hte-icpm-01.htejcap.caltech.edu
    port: 8010
    group: action
    fast: dbpack_server
    params:
      aws_profile: default
      testing: false
  ANA:
    host: hte-icpm-01.htejcap.caltech.edu
    port: 8014
    group: action
    fast: analysis_server
    params:
      local_only: false