dummy: false
simulation: false
experiment_libraries:
  - samples_exp
  - XRFS_exp
  - helao\deploy\test\experiments\TEST_exp.py
sequence_libraries:
  - XRFS_seq
  - helao\deploy\test\sequences\TEST_seq.py
run_type: xrfs
root: C:\INST_hlo
servers:
  ORCH:
    host: hte-xrfs-01.htejcap.caltech.edu
    port: 8001
    group: orchestrator
    fast: async_orch2
    params: {}
  OPERATOR:
    group: operator
    bokeh: standalone_operator
    host: hte-xrfs-01.htejcap.caltech.edu
    port: 5002
    params:
      orch_key: ORCH
      poll_interval: 5
  PAL:
    host: hte-xrfs-01.htejcap.caltech.edu
    port: 8007
    group: action
    fast: pal_server
    params:
      positions:
        custom:
          cell1_we: cell
  DB:
    host: hte-xrfs-01.htejcap.caltech.edu
    port: 8010
    group: action
    fast: dbpack_server
    params:
      aws_profile: default
      testing: false
      auto_analyze_sequences:
        XRFS_noStandards:
          server_key: ANA
          host: hte-xrfs-01.htejcap.caltech.edu
          port: 8014
          endpoint: analyze_xrfs_local
  ANA:
    host: hte-xrfs-01.htejcap.caltech.edu
    port: 8014
    group: action
    fast: analysis_server
    params:
      local_only: false
      analyses: [icpms_local, xrfs_local]